### ISSUE TITLE
No dependencies installed

### ISSUE THREAD

**Issue by MrHarcombe** [dr4ke616/MMM-Voice-Control#1]
Hiya - this looks really great (my 12yo son is very excited about the possibilities...) but we're having problems getting it all going. In your notes you say to clone it and then run `npm install` but there are no dependencies listed to be installed. Is that correct, as we can't seem to get this running as is?

**Comment by dr4ke616** [comment]
Hey @MrHarcombe, apologies for that, that is a error in my README. There are no external dependancies required as I have `annyang.js` checked-in locally (Im not a JS developer, so this is probably considered bad practice).

**Comment by dr4ke616** [comment]
I have updated the README to fix this.

**Comment by MrHarcombe** [comment]
Cool, thank you.
